#!/bin/bash
pkill dhcpcd
pkill dhclient 
pkill wpa_supplicant
echo "running eth0 down"
ifconfig eth0 down
echo "running wpa_supplicant"
wpa_supplicant -D wext -i wlan0 -c /etc/wpa_baker.conf & #> /dev/null 2>&1 &
echo "running iwconfig"
iwconfig wlan0 mode managed channel 1 essid baker
#iwconfig wlan0 ap 00:1C:10:3C:76:61
#dhcpcd -nd wlan0
echo "running dhclient"
#dhclient wlan0 #> /dev/null 2>&1
dhcpcd wlan0
#ifconfig wlan0 192.168.1.102
echo "Got $(ifconfig wlan0|egrep "inet addr"|awk -F" " '{print $2}' |awk -F":" '{print $2}')"
