#!/bin/bash
timestamp=$(date +%s)
hostname=$(hostname)
kent="./kent"
pushd '/mnt/stick'
if [[ -d "$kent" ]] ; then
    echo "$kent exists. backing it up..." 
    /bin/tar cjvf $hostname.$timestamp.tar.bz2 $kent
    echo "Deleting old $kent"
    rm -Rfv $kent
fi

echo "copying new $kent"
/bin/cp -Rv '/home/httpd/html/codex/kent' .
