#!/bin/bash
STATIC=main
LINK=0k2srzdf.default
VOLATILE=/dev/shm/noah/firefox

cd ~/.mozilla/firefox

[[ -r $VOLATILE ]] || install -dm700 $VOLATILE

if [[ `readlink $LINK` != $VOLATILE ]]; then
  mv $LINK $STATIC
  ln -s $VOLATILE $LINK
fi

if [[ -e $LINK/.unpacked ]]; then
  rsync -av --delete --exclude .unpacked ./$LINK/ ./$STATIC/
else
  rsync -av ./$STATIC/ ./$LINK/
  touch $LINK/.unpacked
fi
