#!/bin/bash

# simplify gnupod_addsong.pl syntax
#
# point it at a directory to add all .mp3 recursively

if [ "$1" == "" ]; then
  echo "$0 <dir>"
  exit
fi

while [ $# -ne 0 ]; do
  #find "$1" -iname "*.mp3" -exec gnupod_addsong.pl {} 2>/dev/null \; 
  find "$1" -type d -exec echo $(bash -c ls {}/*.mp3) \;
  shift
done

#mktunes.pl 2> /dev/null

df -h|grep ipod
