#!/bin/sh

set -u
set -e

# git-create-linked
#
#   Given a string $identifier, 
#       Login to bare repo server
#       Create a bare repo named $identifier
#       Logout of bare repo server
#       Check out a local copy of the remote bare repo named $idenfier
#       cd to the directory

remote_user="noah"
remote_host="0x7be.org"
remote_bare_basepath="/home/noah/gits/bare"
local_checkout_basepath="/home/noah/gits/checkouts"

if [[ ! ($# -eq 1) ]]; then
  echo "Usage: $0 <identifier>"
  exit -1
fi

remote_bare_repo="$remote_bare_basepath/$1"
echo "Creating bare $remote_bare_repo on $remote_host"
ssh "$remote_user@$remote_host" \
    "git init --bare $remote_bare_repo"

local_repo="$local_checkout_basepath/$1"
echo "Creating local $local_repo"
pushd "$local_checkout_basepath"
git clone "$remote_user@$remote_host:$remote_bare_repo"
pushd "$local_repo"
touch README.md
git add README.md
git commit -a -m'initial readme commit'
git push origin master
echo "Done"
