#!/bin/bash
TARGET=`basename $1`
ANNOUNCE_URL="http://cheggit.net/announce"
BITTORRENT_PORT="49999"
echo "making $TARGET.torrent"
createtorrent -a $ANNOUNCE_URL -p $BITTORRENT_PORT $TARGET $TARGET.torrent
