#!/bin/bash
pkill dhcpcd
pkill dhclient 
pkill wpa_supplicant
ifconfig eth0 down
wpa_supplicant -D wext -i wlan0 -c /etc/wpa_supplicant_uc.conf > /dev/null 2>&1 &
iwconfig wlan0 mode managed essid uc
#iwconfig wlan0 ap 00:1C:10:3C:76:61
#dhcpcd -nd wlan0
dhclient wlan0 > /dev/null 2>&1
#ifconfig wlan0 192.168.1.102
echo "Got $(ifconfig wlan0|egrep "inet addr"|awk -F" " '{print $2}' |awk -F":" '{print $2}')"
